//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

#[cfg(feature = "ssr")]
pub mod server {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
    #[sea_orm(table_name = "seen_messages")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub message_id: i32,
        #[sea_orm(primary_key, auto_increment = false)]
        pub seen_id: i32,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {
        #[sea_orm(
            belongs_to = "crate::entities::message::server::Entity",
            from = "Column::MessageId",
            to = "crate::entities::message::server::Column::Id",
            on_update = "Restrict",
            on_delete = "Cascade"
        )]
        Message2,
        #[sea_orm(
            belongs_to = "crate::entities::message::server::Entity",
            from = "Column::SeenId",
            to = "crate::entities::message::server::Column::Id",
            on_update = "Restrict",
            on_delete = "Cascade"
        )]
        Message1,
    }

    impl ActiveModelBehavior for ActiveModel {}
}
