//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

#[cfg(feature = "ssr")]
pub mod server {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
    #[sea_orm(table_name = "seen_messages")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        pub message_id: i32,
        #[sea_orm(primary_key, auto_increment = false)]
        pub seen_id: i32,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {
        #[sea_orm(
            belongs_to = "crate::entities::message::server::Entity",
            from = "Column::MessageId",
            to = "crate::entities::message::server::Column::MessageId",
            on_update = "Restrict",
            on_delete = "Cascade"
        )]
        Message,
        #[sea_orm(
            belongs_to = "crate::entities::users::server::Entity",
            from = "Column::SeenId",
            to = "crate::entities::users::server::Column::Id",
            on_update = "Restrict",
            on_delete = "Cascade"
        )]
        Users,
    }

    impl Related<crate::entities::message::server::Entity> for Entity {
        fn to() -> RelationDef {
            Relation::Message.def()
        }
    }

    impl Related<crate::entities::users::server::Entity> for Entity {
        fn to() -> RelationDef {
            Relation::Users.def()
        }
    }

    impl ActiveModelBehavior for ActiveModel {}
}
