//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

#[cfg(feature = "ssr")]
pub mod server {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
    #[sea_orm(table_name = "temp_users")]
    pub struct Model {
        #[sea_orm(primary_key)]
        pub id: i32,
        pub first_name: String,
        pub last_name: String,
        pub email: String,
        pub phone_number: i64,
        pub password: String,
        pub verification: String,
        pub time: DateTimeUtc,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}
